services:
  db:
    image: postgres:14
    container_name: cinema-booking-db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5435:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - type: bind
        source: /root/env/.env
        target: /app/.env
        read_only: true

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cinema-booking-app
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - type: bind
        source: /root/env/.env
        target: /app/.env
        read_only: true

  nginx:
      image: nginx:stable
      container_name: cinema-booking-nginx
      ports:
        - "80:80"
      volumes:
        - ./nginx/conf.d:/etc/nginx/conf.d
      depends_on:
        - app

volumes:
  postgres-data: